spring:
  application:
    name: leo
  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@localhost:${MONGO_APP_PORT}/${MONGO_APP_DATABASE}?authSource=admin

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8080
